/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Command,
  CommandCreate,
  CommandPage,
  Problem,
} from '../models/index';
import {
    CommandFromJSON,
    CommandToJSON,
    CommandCreateFromJSON,
    CommandCreateToJSON,
    CommandPageFromJSON,
    CommandPageToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface CreateDeviceCommandRequest {
    idempotencyKey: string;
    tenantId: string;
    corelinkDeviceId: string;
    commandCreate: CommandCreate;
}

export interface GetDeviceCommandRequest {
    tenantId: string;
    corelinkDeviceId: string;
    commandId: string;
}

export interface ListDeviceCommandsRequest {
    tenantId: string;
    corelinkDeviceId: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class CommandsApi extends runtime.BaseAPI {

    /**
     */
    async createDeviceCommandRaw(requestParameters: CreateDeviceCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Command>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createDeviceCommand().'
            );
        }

        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling createDeviceCommand().'
            );
        }

        if (requestParameters['corelinkDeviceId'] == null) {
            throw new runtime.RequiredError(
                'corelinkDeviceId',
                'Required parameter "corelinkDeviceId" was null or undefined when calling createDeviceCommand().'
            );
        }

        if (requestParameters['commandCreate'] == null) {
            throw new runtime.RequiredError(
                'commandCreate',
                'Required parameter "commandCreate" was null or undefined when calling createDeviceCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tenants/{tenant_id}/devices/{corelink_device_id}/commands`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"corelink_device_id"}}`, encodeURIComponent(String(requestParameters['corelinkDeviceId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommandCreateToJSON(requestParameters['commandCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandFromJSON(jsonValue));
    }

    /**
     */
    async createDeviceCommand(requestParameters: CreateDeviceCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Command> {
        const response = await this.createDeviceCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDeviceCommandRaw(requestParameters: GetDeviceCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Command>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getDeviceCommand().'
            );
        }

        if (requestParameters['corelinkDeviceId'] == null) {
            throw new runtime.RequiredError(
                'corelinkDeviceId',
                'Required parameter "corelinkDeviceId" was null or undefined when calling getDeviceCommand().'
            );
        }

        if (requestParameters['commandId'] == null) {
            throw new runtime.RequiredError(
                'commandId',
                'Required parameter "commandId" was null or undefined when calling getDeviceCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tenants/{tenant_id}/devices/{corelink_device_id}/commands/{command_id}`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"corelink_device_id"}}`, encodeURIComponent(String(requestParameters['corelinkDeviceId']))).replace(`{${"command_id"}}`, encodeURIComponent(String(requestParameters['commandId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandFromJSON(jsonValue));
    }

    /**
     */
    async getDeviceCommand(requestParameters: GetDeviceCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Command> {
        const response = await this.getDeviceCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDeviceCommandsRaw(requestParameters: ListDeviceCommandsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandPage>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling listDeviceCommands().'
            );
        }

        if (requestParameters['corelinkDeviceId'] == null) {
            throw new runtime.RequiredError(
                'corelinkDeviceId',
                'Required parameter "corelinkDeviceId" was null or undefined when calling listDeviceCommands().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tenants/{tenant_id}/devices/{corelink_device_id}/commands`.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId']))).replace(`{${"corelink_device_id"}}`, encodeURIComponent(String(requestParameters['corelinkDeviceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandPageFromJSON(jsonValue));
    }

    /**
     */
    async listDeviceCommands(requestParameters: ListDeviceCommandsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandPage> {
        const response = await this.listDeviceCommandsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
