/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Command } from './Command';
import {
    CommandFromJSON,
    CommandFromJSONTyped,
    CommandToJSON,
    CommandToJSONTyped,
} from './Command';

/**
 * 
 * @export
 * @interface CommandPage
 */
export interface CommandPage {
    /**
     * 
     * @type {Array<Command>}
     * @memberof CommandPage
     */
    items: Array<Command>;
    /**
     * 
     * @type {number}
     * @memberof CommandPage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof CommandPage
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof CommandPage
     */
    offset: number;
}

/**
 * Check if a given object implements the CommandPage interface.
 */
export function instanceOfCommandPage(value: object): value is CommandPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function CommandPageFromJSON(json: any): CommandPage {
    return CommandPageFromJSONTyped(json, false);
}

export function CommandPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CommandFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function CommandPageToJSON(json: any): CommandPage {
    return CommandPageToJSONTyped(json, false);
}

export function CommandPageToJSONTyped(value?: CommandPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CommandToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

