/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CommandStatus = {
    Queued: 'queued',
    Dispatching: 'dispatching',
    Sent: 'sent',
    Acknowledged: 'acknowledged',
    Succeeded: 'succeeded',
    Failed: 'failed',
    TimedOut: 'timed_out',
    Cancelled: 'cancelled'
} as const;
export type CommandStatus = typeof CommandStatus[keyof typeof CommandStatus];


export function instanceOfCommandStatus(value: any): boolean {
    for (const key in CommandStatus) {
        if (Object.prototype.hasOwnProperty.call(CommandStatus, key)) {
            if (CommandStatus[key as keyof typeof CommandStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CommandStatusFromJSON(json: any): CommandStatus {
    return CommandStatusFromJSONTyped(json, false);
}

export function CommandStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandStatus {
    return json as CommandStatus;
}

export function CommandStatusToJSON(value?: CommandStatus | null): any {
    return value as any;
}

export function CommandStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CommandStatus {
    return value as CommandStatus;
}

