/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandCreate
 */
export interface CommandCreate {
    /**
     * 
     * @type {string}
     * @memberof CommandCreate
     */
    commandType: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CommandCreate
     */
    payload?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof CommandCreate
     */
    timeoutAt?: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CommandCreate
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CommandCreate interface.
 */
export function instanceOfCommandCreate(value: object): value is CommandCreate {
    if (!('commandType' in value) || value['commandType'] === undefined) return false;
    return true;
}

export function CommandCreateFromJSON(json: any): CommandCreate {
    return CommandCreateFromJSONTyped(json, false);
}

export function CommandCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'commandType': json['command_type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'timeoutAt': json['timeout_at'] == null ? undefined : (new Date(json['timeout_at'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CommandCreateToJSON(json: any): CommandCreate {
    return CommandCreateToJSONTyped(json, false);
}

export function CommandCreateToJSONTyped(value?: CommandCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command_type': value['commandType'],
        'payload': value['payload'],
        'timeout_at': value['timeoutAt'] == null ? undefined : ((value['timeoutAt']).toISOString()),
        'metadata': value['metadata'],
    };
}

