/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommandStatus } from './CommandStatus';
import {
    CommandStatusFromJSON,
    CommandStatusFromJSONTyped,
    CommandStatusToJSON,
    CommandStatusToJSONTyped,
} from './CommandStatus';

/**
 *
 * @export
 * @interface Command
 */
export interface Command {
    /**
     *
     * @type {string}
     * @memberof Command
     */
    commandId: string;
    /**
     *
     * @type {string}
     * @memberof Command
     */
    tenantId: string;
    /**
     *
     * @type {string}
     * @memberof Command
     */
    corelinkDeviceId: string;
    /**
     *
     * @type {string}
     * @memberof Command
     */
    commandType: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof Command
     */
    payload: { [key: string]: any; };
    /**
     *
     * @type {CommandStatus}
     * @memberof Command
     */
    status: CommandStatus;
    /**
     *
     * @type {number}
     * @memberof Command
     */
    attemptCount: number;
    /**
     *
     * @type {Date}
     * @memberof Command
     */
    timeoutAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof Command
     */
    acknowledgedAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof Command
     */
    completedAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof Command
     */
    errorCode?: string | null;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof Command
     */
    metadata: { [key: string]: any; };
    /**
     *
     * @type {Date}
     * @memberof Command
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof Command
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Command interface.
 */
export function instanceOfCommand(value: object): value is Command {
    if (!('commandId' in value) || value['commandId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('corelinkDeviceId' in value) || value['corelinkDeviceId'] === undefined) return false;
    if (!('commandType' in value) || value['commandType'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attemptCount' in value) || value['attemptCount'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CommandFromJSON(json: any): Command {
    return CommandFromJSONTyped(json, false);
}

export function CommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): Command {
    if (json == null) {
        return json;
    }
    return {

        'commandId': json['command_id'],
        'tenantId': json['tenant_id'],
        'corelinkDeviceId': json['corelink_device_id'],
        'commandType': json['command_type'],
        'payload': json['payload'],
        'status': CommandStatusFromJSON(json['status']),
        'attemptCount': json['attempt_count'],
        'timeoutAt': json['timeout_at'] == null ? undefined : (new Date(json['timeout_at'])),
        'acknowledgedAt': json['acknowledged_at'] == null ? undefined : (new Date(json['acknowledged_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'errorCode': json['error_code'] == null ? undefined : json['error_code'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CommandToJSON(json: any): Command {
    return CommandToJSONTyped(json, false);
}

export function CommandToJSONTyped(value?: Command | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'command_id': value['commandId'],
        'tenant_id': value['tenantId'],
        'corelink_device_id': value['corelinkDeviceId'],
        'command_type': value['commandType'],
        'payload': value['payload'],
        'status': CommandStatusToJSON(value['status']),
        'attempt_count': value['attemptCount'],
        'timeout_at': value['timeoutAt'] == null ? undefined : ((value['timeoutAt'] as any).toISOString()),
        'acknowledged_at': value['acknowledgedAt'] == null ? undefined : ((value['acknowledgedAt'] as any).toISOString()),
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'error_code': value['errorCode'],
        'metadata': value['metadata'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

