/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceCreate
 */
export interface DeviceCreate {
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    deviceModelId: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    partnerSkuId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    firmwareReleaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DeviceCreate
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the DeviceCreate interface.
 */
export function instanceOfDeviceCreate(value: object): value is DeviceCreate {
    if (!('deviceModelId' in value) || value['deviceModelId'] === undefined) return false;
    return true;
}

export function DeviceCreateFromJSON(json: any): DeviceCreate {
    return DeviceCreateFromJSONTyped(json, false);
}

export function DeviceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceModelId': json['device_model_id'],
        'partnerSkuId': json['partner_sku_id'] == null ? undefined : json['partner_sku_id'],
        'firmwareReleaseId': json['firmware_release_id'] == null ? undefined : json['firmware_release_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function DeviceCreateToJSON(json: any): DeviceCreate {
    return DeviceCreateToJSONTyped(json, false);
}

export function DeviceCreateToJSONTyped(value?: DeviceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_model_id': value['deviceModelId'],
        'partner_sku_id': value['partnerSkuId'],
        'firmware_release_id': value['firmwareReleaseId'],
        'name': value['name'],
        'metadata': value['metadata'],
    };
}

