/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DeviceStatus = {
    Inventory: 'inventory',
    Provisioning: 'provisioning',
    Active: 'active',
    Suspended: 'suspended',
    Retired: 'retired'
} as const;
export type DeviceStatus = typeof DeviceStatus[keyof typeof DeviceStatus];


export function instanceOfDeviceStatus(value: any): boolean {
    for (const key in DeviceStatus) {
        if (Object.prototype.hasOwnProperty.call(DeviceStatus, key)) {
            if (DeviceStatus[key as keyof typeof DeviceStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DeviceStatusFromJSON(json: any): DeviceStatus {
    return DeviceStatusFromJSONTyped(json, false);
}

export function DeviceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceStatus {
    return json as DeviceStatus;
}

export function DeviceStatusToJSON(value?: DeviceStatus | null): any {
    return value as any;
}

export function DeviceStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DeviceStatus {
    return value as DeviceStatus;
}

