/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceStatus } from './DeviceStatus';
import {
    DeviceStatusFromJSON,
    DeviceStatusFromJSONTyped,
    DeviceStatusToJSON,
    DeviceStatusToJSONTyped,
} from './DeviceStatus';

/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    corelinkDeviceId: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    deviceModelId: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    partnerSkuId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    firmwareReleaseId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    name?: string | null;
    /**
     * 
     * @type {DeviceStatus}
     * @memberof Device
     */
    status: DeviceStatus;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Device
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof Device
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Device
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Device interface.
 */
export function instanceOfDevice(value: object): value is Device {
    if (!('corelinkDeviceId' in value) || value['corelinkDeviceId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('deviceModelId' in value) || value['deviceModelId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DeviceFromJSON(json: any): Device {
    return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Device {
    if (json == null) {
        return json;
    }
    return {
        
        'corelinkDeviceId': json['corelink_device_id'],
        'tenantId': json['tenant_id'],
        'deviceModelId': json['device_model_id'],
        'partnerSkuId': json['partner_sku_id'] == null ? undefined : json['partner_sku_id'],
        'firmwareReleaseId': json['firmware_release_id'] == null ? undefined : json['firmware_release_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': DeviceStatusFromJSON(json['status']),
        'metadata': json['metadata'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function DeviceToJSON(json: any): Device {
    return DeviceToJSONTyped(json, false);
}

export function DeviceToJSONTyped(value?: Device | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corelink_device_id': value['corelinkDeviceId'],
        'tenant_id': value['tenantId'],
        'device_model_id': value['deviceModelId'],
        'partner_sku_id': value['partnerSkuId'],
        'firmware_release_id': value['firmwareReleaseId'],
        'name': value['name'],
        'status': DeviceStatusToJSON(value['status']),
        'metadata': value['metadata'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

