/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceUpdate
 */
export interface DeviceUpdate {
    /**
     * 
     * @type {string}
     * @memberof DeviceUpdate
     */
    firmwareReleaseId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DeviceUpdate
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the DeviceUpdate interface.
 */
export function instanceOfDeviceUpdate(value: object): value is DeviceUpdate {
    return true;
}

export function DeviceUpdateFromJSON(json: any): DeviceUpdate {
    return DeviceUpdateFromJSONTyped(json, false);
}

export function DeviceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'firmwareReleaseId': json['firmware_release_id'] == null ? undefined : json['firmware_release_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function DeviceUpdateToJSON(json: any): DeviceUpdate {
    return DeviceUpdateToJSONTyped(json, false);
}

export function DeviceUpdateToJSONTyped(value?: DeviceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firmware_release_id': value['firmwareReleaseId'],
        'name': value['name'],
        'metadata': value['metadata'],
    };
}

