/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Device } from './Device';
import {
    DeviceFromJSON,
    DeviceFromJSONTyped,
    DeviceToJSON,
    DeviceToJSONTyped,
} from './Device';

/**
 * 
 * @export
 * @interface DevicePage
 */
export interface DevicePage {
    /**
     * 
     * @type {Array<Device>}
     * @memberof DevicePage
     */
    items: Array<Device>;
    /**
     * 
     * @type {number}
     * @memberof DevicePage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof DevicePage
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof DevicePage
     */
    offset: number;
}

/**
 * Check if a given object implements the DevicePage interface.
 */
export function instanceOfDevicePage(value: object): value is DevicePage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function DevicePageFromJSON(json: any): DevicePage {
    return DevicePageFromJSONTyped(json, false);
}

export function DevicePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevicePage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DeviceFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function DevicePageToJSON(json: any): DevicePage {
    return DevicePageToJSONTyped(json, false);
}

export function DevicePageToJSONTyped(value?: DevicePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(DeviceToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

