/* tslint:disable */
/* eslint-disable */
/**
 * CoreLink Public API
 * Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Problem
 */
export interface Problem {
    /**
     *
     * @type {string}
     * @memberof Problem
     */
    type: string;
    /**
     *
     * @type {string}
     * @memberof Problem
     */
    title: string;
    /**
     *
     * @type {number}
     * @memberof Problem
     */
    status: number;
    /**
     *
     * @type {string}
     * @memberof Problem
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof Problem
     */
    detail?: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof Problem
     */
    diagnostics?: { [key: string]: any; };
    /**
     *
     * @type {string}
     * @memberof Problem
     */
    correlationId: string;
}

/**
 * Check if a given object implements the Problem interface.
 */
export function instanceOfProblem(value: object): value is Problem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('correlationId' in value) || value['correlationId'] === undefined) return false;
    return true;
}

export function ProblemFromJSON(json: any): Problem {
    return ProblemFromJSONTyped(json, false);
}

export function ProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Problem {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'code': json['code'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'diagnostics': json['diagnostics'] == null ? undefined : json['diagnostics'],
        'correlationId': json['correlation_id'],
    };
}

export function ProblemToJSON(json: any): Problem {
    return ProblemToJSONTyped(json, false);
}

export function ProblemToJSONTyped(value?: Problem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'code': value['code'],
        'detail': value['detail'],
        'diagnostics': value['diagnostics'],
        'correlation_id': value['correlationId'],
    };
}

